### PR TITLE
Clear cache if topic not found

### LINKED ISSUE #220: Automatically clear cache & retry if `dev_help()` fails
Where fails = generates a path that doesn't exist.

### PR DESCRIPTION
**Pull request by hadley**
Most of the work here was making it possible to work on this - now calling `load_all()` on pkgload will force reload the shims so you get the development version. Also refactored `dev_topic_find()` to make it a bit clearer what it's doing.

Fixes #220

### CODE REVIEW

File: R/dev-help.R [hunk 1]
```diff
@@ -26,9 +26,16 @@ dev_help <- function(topic,
                      dev_packages = NULL,
                      stage = "render",
                      type = getOption("help_type")) {
+
```
Comment (lionel-) [inline R/dev-help.R:29]:
```suggestion
```

File: R/dev-help.R [hunk 2]
```diff
@@ -26,9 +26,16 @@ dev_help <- function(topic,
...
   loc <- dev_topic_find(topic, dev_packages)
 
-  if (is.null(loc$path)) {
+  if (!is.null(loc$path) && !file.exists(loc$path)) {
```
Comment (lionel-) [inline R/dev-help.R:32]: Should we use fs consistently in this package since we depend on it?

File: R/shims.R [hunk 3]
```diff
@@ -10,9 +10,15 @@ insert_imports_shims <- function(package) {
...
-  # If shims already present, just return
-  if ("devtools_shims" %in% search()) return()
+insert_global_shims <- function(force = FALSE) {
+  if ("devtools_shims" %in% search()) {
+    if (force) {
+      base::detach("devtools_shims")
+    } else {
+      # If shims already present, just return
+      return()
+    }
```
Comment (lionel-) [inline R/shims.R:20]: I think control flow would be clearer this way (if one branch returns, ideally all branches should for symmetry)

```suggestion
    if (!force) {
      # If shims already present, just return
      return()
    }
    base::detach("devtools_shims")
```

File: R/zzz.R [hunk 4]
```diff
@@ -2,6 +2,11 @@
   run_on_load()
   ns <- ns_env(pkgname)
 
+  # Force reload global shims if developing pkgload itself
+  if (is_loading()) {
+    insert_global_shims(TRUE)
```
Comment (lionel-) [inline R/zzz.R:7]: Self-documenting named argument:

```suggestion
    insert_global_shims(force = TRUE)
```

File: tests/testthat/test-help.R [hunk 5]
```diff
@@ -72,6 +72,23 @@ test_that("show_help and shim_question files for devtools-loaded packages", {
...
+  on.exit(unload(test_path('testHelp')))
+
+  foofoo_path <- test_path("testHelp/man/foofoo.Rd")
+  barbar_path <- test_path("testHelp/man/barbar.Rd")
+
+  expect_equal(shim_help("foofoo")$path, normalizePath(foofoo_path))
+  expect_equal(shim_question("foofoo")$path, normalizePath(foofoo_path))
+
+  file.rename(foofoo_path, barbar_path)
+  on.exit(file.rename(barbar_path, foofoo_path))
```
Comment (lionel-) [inline tests/testthat/test-help.R:86]:
```suggestion
  on.exit(file.rename(barbar_path, foofoo_path), add = TRUE)
```

**Review by lionel- — APPROVED** [review]
One of the new tests seem to be failing.
